### ISSUE TITLE
Version 1.0.7:  incompatibily pod versions for iOS

### ISSUE THREAD

**Issue by alien190** [freestarcapital/freestar_flutter_plugin#13]
After migration to  freestar_flutter_plugin: ^1.0.7

Commands:

`flutter build ios`
and 
`pod update`

fail with error:

```
[!] CocoaPods could not find compatible versions for pod "GoogleAds-IMA-iOS-SDK":
  In Podfile:
    FreestarAds-Google (~> 5.0) was resolved to 5.0.0, which depends on
     GoogleAds-IMA-iOS-SDK (= 3.14.1)

    FreestarAds-Nimbus (~> 3.0) was resolved to 3.0.0, which depends on
      NimbusSDK/NimbusRenderVideoKit (= 1.10.2) was resolved to 1.10.2, which depends on
        GoogleAds-IMA-iOS-SDK (= 3.13.0)
```

The building attempt of the example app https://github.com/freestarcapital/freestar_flutter_plugin/tree/main/example fails with the same error.

**Comment by kkawai** [comment]
Hello @alien190 Thank you for letting us know.  Will resolve the issue soon.

**Comment by kkawai** [comment]
@alien190 Hello!  We have fixed the iOS issue and updated our plugin.  Thank you for your feedback.

**Comment by alien190** [comment]
@kkawai Hello! Thanks s lot for the quick fixing up. The new version 1.0.10 is built successfully for iOS.
