### ISSUE TITLE
Android build issue with HyprMX-SDK:6.0.1

### ISSUE THREAD

**Issue by alien190** [freestarcapital/freestar_flutter_plugin#16]
After upgrading to latest dependencies as described here
https://github.com/freestarcapital/SDK_documentation_Android/wiki/Freestar-Ads-Mediation---Android#dependencies

the build fails with error:

`* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
 Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
    Could not resolve com.hyprmx.android:HyprMX-SDK:6.0.1.
     Required by:
         project :app
        Could not resolve com.hyprmx.android:HyprMX-SDK:6.0.1.
           Could not get resource 'https://s3.amazonaws.com/moat-sdk-builds/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.pom'.
             Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.pom'. Received status code 403 from server: Forbidden`

**Comment by kkawai** [comment]
Hello, we have fixed the plugin in 1.0.12 to include HyprMX.  Thanks for
letting us know.

**Comment by alien190** [comment]
@kkawai Thank you very much, now it works fine!
